services:
  selenium-driver:
    image: selenium/standalone-firefox:latest
    container_name: selenium-driver
    ports:
      - "4444:4444"
    networks:
      - selenium-network

  selenium:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: selenium
    depends_on:
      - selenium-driver
    environment:
      - DISPLAY=:99
    volumes:
      - ./src/:/app/src/
      - ./profile/:/app/profile/
      - ./out/:/app/out/
    networks:
      - selenium-network
    stdin_open: true
    tty: true
    #command: tail -f /dev/null
    command: python src/main.py

networks:
  selenium-network:
    driver: bridge
